title: COPC â€“ Cloud Optimized Point Cloud
description: Range-readable, compressed, organized LASzip specification

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
